package com.qut.webservices.igalogicservices.models

import com.fasterxml.jackson.annotation.JsonInclude
import com.fasterxml.jackson.annotation.JsonView
import com.fasterxml.jackson.databind.annotation.JsonSerialize
import com.fasterxml.jackson.databind.ser.std.ToStringSerializer
import com.qut.webservices.igalogicservices.rules.core.Sensitive
import io.swagger.v3.oas.annotations.media.Schema
import kotlinx.datetime.LocalDate

/**
* IAM Logic Services
* Business Logic service supporting the IAM integration layer for Saviynt
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

@JsonInclude(JsonInclude.Include.NON_NULL)
data class Calculated (
        var alumniStudent: Boolean? = null,
        var appointeeStaff: Boolean? = null,
        var currentApplicant: Boolean? = null,
        var currentSessionalStaff: Boolean? = null,
        var currentStaff: Boolean? = null,
        var currentStudent: Boolean? = null,
        var currentEpeStudent: Boolean? = null,
        var currentCourseEnrolments: Array<CalculatedCourseEnrolment>? = null,
        var currentCourseAttempts: Array<CalculatedCourseEnrolment>? = null,
        var currentOccupancies: Array<Occupancy>? = null,
        var singleOccupancyPerJobId: Array<Occupancy>? = null,
        var graduandStudent: Boolean? = null,
        var externalStudent: Boolean? = null,
        var undergraduateStudent: Boolean? = null,
        @Schema(description = "This field currently is not used. Boomi's using the value in Person.givenName")
        var cleanGivenName: String? = null,
        @Sensitive
        @JsonView(Sensitive::class)
        var cleanFamilyName: String? = null,
        @Sensitive
        @JsonView(Sensitive::class)
        var displayName: String? = null,
        var locationText: String? = null,
        var employeeReloaded: Boolean? = null,
        var managerReversLookup: ReverseLookup? = null,
        var staffEmailRole: String? = null,
        var staffFinalTermDate: String? = null,
        @JsonSerialize(using = ToStringSerializer::class)
        var firstCommencementDate: LocalDate? = null,
        @JsonSerialize(using = ToStringSerializer::class)
        var finalTerminationDate: LocalDate? = null,
        var newStaff: Boolean? = null,
        var studentReloaded: Boolean? = null,
        var iasRoleCode: String? = null,
        var newStudent: Boolean? = null,
        var supervisor: Boolean? = null,
        var firstSemester: Boolean? = null,
        var intermitStudent: Boolean? = null,
        var deleted: Boolean? = null,
        var offshoreInternationalStudent: Boolean? = null,
        var onshoreInternationalStudent: Boolean? = null,
        var postGraduateStudent: Boolean? = null,
        var postGraduateResearchStudent: Boolean? = null,
        var postGraceStudent: Boolean? = null,
        var postGraceStaff: Boolean? = null,
        var sanction: String? = null,
        var sanctionHold: String? = null,
        var sanctionLevel: String? = null,
        var byod: Boolean? = null,
        var floor: String? = null,
        var room: String? = null,
        var nonAwardStudent: Boolean? = null,
        var otherAwardStudent: Boolean? = null,
        var fullTimeStudent: Boolean? = null,
        var partTimeStudent: Boolean? = null,
        var oesStudent: Boolean? = null,
        var bestOccupancy: Occupancy? = null,
//    var bestCurrentOccupancy: Occupancy? = null,
        var bestOccupancyDepartmentCode: String? = null,
        var bestOccupancyDivisionCode: String? = null,
        var bestOccupancyClevel: String? = null,
        var bestOccupancyEmploymentStatus: String? = null,
        var bestOccupancyType: String? = null,
        @JsonSerialize(using = ToStringSerializer::class)
        var bestOccupancyStartDate: LocalDate? = null,
        @JsonSerialize(using = ToStringSerializer::class)
        var bestOccupancyEndDate: LocalDate? = null,
        var bestOccupancyManagerPositionNumber: String? = null,
        var bestOccupancyPositionClassification: String? = null,
        var bestOccupancyPositionCategory: String? = null,
        var bestOccupancyPositionNumber: String? = null,
        var bestOccupancyPositionTitle: String? = null,
        var bestCourse: String? = null,
        var bestCourseCode: String? = null,
        var bestCourseTypeCode: String? = null,
        var byodEligible: Boolean? = null,
        var unitEnrolmentsString: String? = null,
        var currentUnitEnrolments: Array<CalculatedUnitEnrolment>? = null,
        var courseRoles: Array<CourseRole>? = null,
        var unitRoles: Array<UnitRole>? = null,
        var cLevelRoles: Array<CLevelRole>? = null,
        var facultyRoles: Array<FacultyRole>? = null,
        var epeRoles: Array<EpeRole>? = null,
        var scheduledReprocessing: MutableList<Reprocess> = mutableListOf(),
        var igaUserCreated: Boolean? = null,
        var shouldCreateIgaUser: Boolean? = null,
        var personalPhone: String? = null,
        var personalMobile: String? = null,
        var personalEmail: String? = null,
        var accountCode: String? = null,
        var clevelDescHierarchy: String? = null,
        var roleCode: String? = null
)
