package com.qut.webservices.igalogicservices.models

import com.fasterxml.jackson.annotation.JsonInclude
import com.fasterxml.jackson.annotation.JsonView
import com.qut.webservices.igalogicservices.rules.core.Sensitive

/**
 * IAM Logic Services
 * Business Logic service supporting the IAM integration layer for Saviynt
 *
 * OpenAPI spec version: 1.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 * @param citizenshipCode
 * @param deleted
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
data class Citizenship (
        @Sensitive
        @JsonView(Sensitive::class)
        val citizenshipCode: String? = null,
        val deleted: Boolean,
) {

}

