package com.qut.webservices.igalogicservices.models

import com.fasterxml.jackson.annotation.JsonInclude

/**
* IAM Logic Services
* Business Logic service supporting the IAM integration layer for Saviynt
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/**
 *
 * @param studentId
 * @param employeeId
 * @param igaUserId 
 * @param studentAccountId
 * @param staffAccountId
 * @param iamClientId
 * @param calculated 
 * @param person 
 * @param location
 * @param roles
 * @param cards
 * @param message
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
data class EnrichedIdentity (
    var studentId: String? = null,
    var employeeId: String? = null,
    var igaUserId: String? = null,
    var studentAccountId: Int? = null,
    var staffAccountId: Int? = null,
    var iamClientId: Int? = null,
    var calculated: Calculated? = null,
    var person: Person? = null,
    var location: Location? = null,
    var roles: Array<Role>? = null,
    var cards: Array<Card>? = null,
    var message: String? = null,
    var qutUsername: String? = null,
) {

    constructor(message: String) : this(null, null, null, null, null, null, null, null, null, null, null, message, null )

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as EnrichedIdentity

        if (studentId != other.studentId) return false
        if (employeeId != other.employeeId) return false
        if (igaUserId != other.igaUserId) return false
        if (studentAccountId != other.studentAccountId) return false
        if (staffAccountId != other.staffAccountId) return false
        if (iamClientId != other.iamClientId) return false
        if (calculated != other.calculated) return false
        if (person != other.person) return false
        if (location != other.location) return false
        if (roles != null) {
            if (other.roles == null) return false
            if (!roles.contentEquals(other.roles)) return false
        } else if (other.roles != null) return false
        if (cards != null) {
            if (other.cards == null) return false
            if (!cards.contentEquals(other.cards)) return false
        } else if (other.cards != null) return false
        if (message != other.message) return false
        if (qutUsername != other.qutUsername) return false
        return true
    }

    override fun hashCode(): Int {
        var result = igaUserId?.hashCode() ?: 0
        result = 31 * result + (studentId?.hashCode() ?: 0)
        result = 31 * result + (employeeId?.hashCode() ?: 0)
        result = 31 * result + (studentAccountId ?: 0)
        result = 31 * result + (staffAccountId ?: 0)
        result = 31 * result + (iamClientId ?: 0)
        result = 31 * result + (calculated?.hashCode() ?: 0)
        result = 31 * result + (person?.hashCode() ?: 0)
        result = 31 * result + (location?.hashCode() ?: 0)
        result = 31 * result + (roles?.contentHashCode() ?: 0)
        result = 31 * result + (cards?.contentHashCode() ?: 0)
        result = 31 * result + (message?.hashCode() ?: 0)
        result = 31 * result + (qutUsername?.hashCode() ?: 0)
        return result
    }
}

