/**
* IAM Logic Services
* Business Logic service supporting the IAM integration layer for Saviynt
*
* OpenAPI spec version: 1.0.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.qut.webservices.igalogicservices.models

import com.fasterxml.jackson.annotation.JsonInclude
import com.fasterxml.jackson.databind.annotation.JsonSerialize
import com.fasterxml.jackson.databind.ser.std.ToStringSerializer
import kotlinx.datetime.LocalDate


/**
 * 
 * @param courseCode 
 * @param deleted 
 * @param endDate 
 * @param startDate 
 * @param studentId 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
data class EpeCourse (
        val studentId: String,
        val courseCode: String,
        val courseId: String? = null,
        val courseTitle: String? = null,
        val lmsIntegrationStatus: String? = null,
        val hedStatus: String? = null,
        @JsonSerialize(using = ToStringSerializer::class)
        val startDate: LocalDate,
        @JsonSerialize(using = ToStringSerializer::class)
        val endDate: LocalDate? = null,
) {

}

