/**
* IAM Logic Services
* Business Logic service supporting the IAM integration layer for Saviynt
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.qut.webservices.igalogicservices.models


/**
 * 
 * @param message A human readable error message
 */
data class Error (
    /* A human readable error message */
    val message: kotlin.String
) {

}

